/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CartDrawer: typeof import('./src/components/CartDrawer.vue')['default']
    Criar: typeof import('./src/components/Criar.vue')['default']
    Depoimentos: typeof import('./src/components/Depoimentos.vue')['default']
    HeaderCarrinho: typeof import('./src/components/headerCarrinho.vue')['default']
    HeaderProduto: typeof import('./src/components/headerProduto.vue')['default']
    HeroVideo: typeof import('./src/components/HeroVideo.vue')['default']
    Rodape: typeof import('./src/components/Rodape.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sobre: typeof import('./src/components/Sobre.vue')['default']
  }
}
